# Generated by Django 6.1.1 on 2026-09-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_index=True, max_length=64)),
                ('first_name', models.CharField(max_length=30)),
                ('avatar', models.CharField(choices=[('fox', '🦊'), ('cat', '🐱'), ('panda', '🐼'), ('frog', '🐸'), ('rabbit', '🐰'), ('lion', '🦁')], default='fox', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=12)),
                ('table', models.PositiveSmallIntegerField()),
                ('questions', models.JSONField()),
                ('answers', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.profile')),
            ],
        ),
    ]
