# Generated by Django 6.1.1 on 2026-09-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_questions', models.PositiveBigIntegerField(default=0, verbose_name='réponses validées')),
                ('completed_series', models.PositiveBigIntegerField(default=0, verbose_name='séries terminées')),
            ],
            options={
                'verbose_name': 'compteur d’utilisation',
                'verbose_name_plural': 'compteurs d’utilisation',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='usage_counter_singleton')],
            },
        ),
    ]
